nome = str(input ("Digite o nome do cliente:"))
dia_venc = str(input ("Digite o dia de vencimento: "))
mes_venc = str(input ("Digite o mês de vencimento: "))
valor_fatura = str(input ("Valor da fatura: "))
print ("Olá ", nome)
print ("Sua fatura no valor de", valor_fatura, "reais, com vencimento no dia ", dia_venc, " de ", mes_venc, "está fechada")
